issue 50 対応
HIJIKIsw/FlappyKazuha pull request #156
Opened 2023-10-14 19:16 UTC by shulapowerman

#50 テキストはソースコードにベタ書き
左クリックでテキスト変更、時間経過によるテキスト変更を実装

2023-10-14 19:55 UTC, HIJIKIsw requested changes

2023-10-14 19:55 UTC, HIJIKIsw commented on Assets/App/Scripts/UI/Loading/Loading2.cs
> +		private void SetTips()
SetTips() という名前だと「Tipsをセットする」という意味になるが、
何をセットするのかが明示的でない気がします。

- 案1
  - メソッド名を ChangeTips() に変更する
- 案2
  - SetTips(string tipsText) としてセットするTipsのテキストを引数で受け取るようにする
  - GetNextTipsNumber() メソッドを実装して、次に表示すべきTipsの番号を取得する
  - GetTipsTextByNumber(int number) メソッドを実装して、Tipsの番号からTipsのテキストを取得できるようにする
  - これら実装した上で、GetNextTipsNumber() → GetTipsTextByNumber(int number) → SetTips(string tipsText) と呼ぶイメージ
- 案3
  - 案2をちょっと省略して GetNextTipsText() → SetTips(string tipsText) みたいにする

案2や3のほうがキレイだけど今は案1でもいい。

2023-10-14 19:55 UTC, HIJIKIsw commented on Assets/App/Scripts/UI/Loading/Loading2.cs
> +		float timeCount;
何の時間をカウントする変数なのかを明示的にしてください。

- tipsUpdateRemainTime
- tipsChangeInterval
などなど...

2023-10-14 19:55 UTC, HIJIKIsw commented on Assets/App/Scripts/UI/Loading/Loading2.cs
> +			}
これらの if は or 条件で共通化できそうです。

2023-10-14 19:55 UTC, HIJIKIsw commented on Assets/App/Scripts/UI/Loading/Loading2.cs
> +			}
Issueに詳しく書けてなくて申し訳ないですが、Tipsのテキスト文言自体は現時点ではソースコードにベタ書きでも大丈夫だけど、Tipsテキストの総数が増減したときに表示を切り替える部分のロジックをいじらなくて済むような形にしておく必要があるので修正お願いします。
(Tipsテキストは増減の頻度が多いと思う)

- 配列を使う
- `List<string>`を使う

2023-10-15 04:51 UTC, shulapowerman commented on Assets/App/Scripts/UI/Loading/Loading2.cs
> +		float timeCount;
41行目のことであってる？

2023-10-15 04:54 UTC, HIJIKIsw commented on Assets/App/Scripts/UI/Loading/Loading2.cs
> +		float timeCount;
hai!
41行目クリックしてコメントつけたはずなのに分かりづらいなこれ🙇‍♂️

2023-11-13 16:40 UTC, HIJIKIsw approved these changes

2023-11-15 00:36 UTC, merged